### ISSUE TITLE
Support for context manager

### ISSUE THREAD

**Issue by keehun** [Themis3000/lazy_db#2]
* lazy_db version: 1.0.1

### Description
If Python encounters an error/exception before `db.close()`, the database may not be closed properly. I recommend the addition of context managers that will gracefully handle exceptions. It may look like something like this:

```python
db = LazyDb('test.lzdb')
with db.open():
    some_function_that_may_raise_error()
    db.write()
```

**Comment by Themis3000** [comment]
Thank you for your detailed feature request. I've added the feature in #3 and will be merging to master & deploying to pypi under version 1.1.0 momentarily.

I've chosen to use a slightly different style of implementation. Since there is no LazyDb.open() method right now and the db file is opened during the initialization of LazyDb currently, I choose to implement usage that looks more like this similar as to how the context manager is used with the open() method:

```python
with LazyDb('test.lzdb') as db:
    some_function_that_may_raise_error()
    db.write()
```
