### ISSUE TITLE
update data

### ISSUE THREAD

**Issue by dineshbvadhia** [Themis3000/lazy_db#6]
Can data be updated using an existing key?

**Comment by Themis3000** [comment]
> Can data be updated using an existing key?

Hi, currently updating using an existing key is not a feature that exists. It is however very easy to implement and I do plan to do so in the future. I'm a bit busy right now, but I will add it in the near future. In the mean time if you wish to use this package, you will have to remove then re-add an existing value instead of updating it. Be aware that although stable, this package is considered to be in alpha still and as such is missing some basic features.
